### ISSUE TITLE
Doubt in arrays program

### ISSUE THREAD

**Issue by lyt3ral** [TharunBalaji2004/Alpha3.0-DSA#2]
Why have you used this approach to solve max subarray sum?

**Comment by TharunBalaji2004** [comment]
Basically I have used three approaches to solve this problem,
1) Naive Approach
2) Prefix Sum Method
3) Kadane's Algorithm

**Comment by TharunBalaji2004** [comment]
Basically I have used three approaches to solve this problem,
1) Naive Approach
2) Prefix Sum Method
3) Kadane's Algorithm

**Comment by lyt3ral** [comment]
okay thanks :)
